# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 253289e56df04c3dd43fcaa0fc69e878f94be9159bacaa02e3d7da125df40d4412e343e7e5936edf66cb7fdde2ffb46ccdc004f661ea174aa7b6fbc5cdda8ff8

test:
  secret_key_base: 1c2513387653fcc11ea757f901f2c9a957d17d929fb63fe2291ba0e376e46ccbb83ecc1d951bb6d7fed6af61c5e4604b0ca08ce364e0a805381229d855b78f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
